# Model parameters
system:
  Lx: 4
  Ly: 4
  j1: 1.0
  j2: 0.5
  bc_x: 'periodic'
  bc_y: 'periodic'
  
# DMRG sweep parameters
chi_maxs: [256]

# Lanczos sampling parameters
lanczos:
  Nss: [1, 2] #, 4, 8, 16, 32, 64, 128, 256, 512]
  seeds: [42, 123] # , 999, 7, 6, 5, 4, 3, 2, 1]
  c: 1.0